name: lamaa_live
description: "Lamaa Live App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
